"""empty message

Revision ID: 05a9754fce9f
Revises: 980adefb4fc9
Create Date: 2021-04-01 08:24:58.362577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a9754fce9f'
down_revision = '980adefb4fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claimers__specific__message__read__time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_sender_id', sa.Integer(), nullable=True),
    sa.Column('last_read_time', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claimers__specific__message__read__time')
    # ### end Alembic commands ###
