"""empty message

Revision ID: 0c6ca4d43be8
Revises: 5cffea07a75f
Create Date: 2021-03-09 18:49:46.284708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6ca4d43be8'
down_revision = '5cffea07a75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claimers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claimer_profile_pic', sa.String(length=355), nullable=False),
    sa.Column('claimer_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_application', sa.DateTime(), nullable=False),
    sa.Column('item_category', sa.String(length=30000), nullable=False),
    sa.Column('email', sa.String(length=30000), nullable=True),
    sa.Column('item_desription', sa.String(length=100), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('claimer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['claimer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claimers')
    # ### end Alembic commands ###
