"""empty message

Revision ID: 0d88708ad2d5
Revises: f0000c7cb8a5
Create Date: 2021-02-13 11:02:07.578344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d88708ad2d5'
down_revision = 'f0000c7cb8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_viewers',
    sa.Column('viewer_id', sa.Integer(), nullable=True),
    sa.Column('viewed_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['viewed_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_viewers')
    # ### end Alembic commands ###
