"""empty message

Revision ID: 190a53352ef1
Revises: c00e0df6fe2c
Create Date: 2021-02-12 16:51:27.528919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190a53352ef1'
down_revision = 'c00e0df6fe2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('E_commerce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1500), nullable=True),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('date_of_post', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=1500), nullable=True),
    sa.Column('condition', sa.String(length=1500), nullable=True),
    sa.Column('ram', sa.String(length=1500), nullable=True),
    sa.Column('screen_size', sa.String(length=1500), nullable=True),
    sa.Column('colour', sa.String(length=1500), nullable=True),
    sa.Column('camera', sa.String(length=1500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storage_capacity', sa.String(length=1500), nullable=True),
    sa.Column('type', sa.String(length=1500), nullable=True),
    sa.Column('subtype', sa.String(length=1500), nullable=True),
    sa.Column('processor', sa.String(length=1500), nullable=True),
    sa.Column('number_of_cores', sa.String(length=1500), nullable=True),
    sa.Column('graphics_card', sa.String(length=1500), nullable=True),
    sa.Column('graphics_card_memory', sa.String(length=1500), nullable=True),
    sa.Column('storage_type', sa.String(length=1500), nullable=True),
    sa.Column('operating_system', sa.String(length=1500), nullable=True),
    sa.Column('make', sa.String(length=1500), nullable=True),
    sa.Column('platform', sa.String(length=1500), nullable=True),
    sa.Column('format', sa.String(length=1500), nullable=True),
    sa.Column('gender', sa.String(length=1500), nullable=True),
    sa.Column('size', sa.String(length=1500), nullable=True),
    sa.Column('style', sa.String(length=1500), nullable=True),
    sa.Column('upper_material', sa.String(length=1500), nullable=True),
    sa.Column('outsole_material', sa.String(length=1500), nullable=True),
    sa.Column('material', sa.String(length=1500), nullable=True),
    sa.Column('closure', sa.String(length=1500), nullable=True),
    sa.Column('main_material', sa.String(length=1500), nullable=True),
    sa.Column('main_stone', sa.String(length=1500), nullable=True),
    sa.Column('formulation', sa.String(length=1500), nullable=True),
    sa.Column('scent', sa.String(length=1500), nullable=True),
    sa.Column('volume', sa.String(length=1500), nullable=True),
    sa.Column('tone', sa.String(length=1500), nullable=True),
    sa.Column('target_area', sa.String(length=1500), nullable=True),
    sa.Column('skin_type', sa.String(length=1500), nullable=True),
    sa.Column('benefits', sa.String(length=1500), nullable=True),
    sa.Column('level', sa.String(length=1500), nullable=True),
    sa.Column('duration', sa.String(length=1500), nullable=True),
    sa.Column('service_features', sa.String(length=1500), nullable=True),
    sa.Column('round_the_clock_service', sa.Boolean(), nullable=True),
    sa.Column('type_of_service', sa.String(length=1500), nullable=True),
    sa.Column('service_include', sa.String(length=1500), nullable=True),
    sa.Column('year_of_manufacture', sa.String(length=1500), nullable=True),
    sa.Column('transmission', sa.String(length=1500), nullable=True),
    sa.Column('mileage', sa.String(length=1500), nullable=True),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('E_commerce')
    # ### end Alembic commands ###
