"""adding link 2

Revision ID: 3486ffab0caf
Revises: 4cbedc658398
Create Date: 2021-01-22 10:29:26.540519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3486ffab0caf'
down_revision = '4cbedc658398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('link', sa.String(length=30000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'link')
    # ### end Alembic commands ###
