"""empty message

Revision ID: 38c1025b32d9
Revises: fa5eed2f19b0
Create Date: 2021-02-03 17:46:07.160289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38c1025b32d9'
down_revision = 'fa5eed2f19b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specific__message__read__time',
    sa.Column('message_sender_id', sa.Integer(), nullable=False),
    sa.Column('last_read_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('message_sender_id')
    )
    op.drop_index('ix_tracked_messages_timestamp', table_name='tracked_messages')
    op.drop_table('tracked_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name='tracked_messages_recipient_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='tracked_messages_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tracked_messages_pkey')
    )
    op.create_index('ix_tracked_messages_timestamp', 'tracked_messages', ['timestamp'], unique=False)
    op.drop_table('specific__message__read__time')
    # ### end Alembic commands ###
