"""empty message

Revision ID: 39550e1b4a3c
Revises: 1ba59970c69a
Create Date: 2021-03-02 16:53:28.431620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39550e1b4a3c'
down_revision = '1ba59970c69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report__post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report__post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inappropriate_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offensive_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hate_speech_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inaccurate_info_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='report__post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='report__post_pkey')
    )
    # ### end Alembic commands ###
