"""empty message

Revision ID: 408274878e04
Revises: cc83b161c04a
Create Date: 2021-02-13 11:35:00.297375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408274878e04'
down_revision = 'cc83b161c04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed__posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed__posts')
    # ### end Alembic commands ###
