"""empty message

Revision ID: 4d38b6637905
Revises: 39d8d1919600
Create Date: 2021-01-18 10:51:39.542601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d38b6637905'
down_revision = '39d8d1919600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('light_sturf_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('light_sturf_update')
    # ### end Alembic commands ###
