"""empty message

Revision ID: 51441e35a980
Revises: 49c54b57b4d2
Create Date: 2021-03-30 06:56:36.722002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51441e35a980'
down_revision = '49c54b57b4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roomie', sa.Column('birth_day', sa.String(length=20), nullable=True))
    op.add_column('roomie', sa.Column('dislikes', sa.String(length=150), nullable=True))
    op.add_column('roomie', sa.Column('likes', sa.String(length=150), nullable=True))
    op.drop_column('user', 'likes')
    op.drop_column('user', 'dislikes')
    op.drop_column('user', 'birth_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_day', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('dislikes', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('likes', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('roomie', 'likes')
    op.drop_column('roomie', 'dislikes')
    op.drop_column('roomie', 'birth_day')
    # ### end Alembic commands ###
