"""empty message

Revision ID: 53c1f1a5fd57
Revises: fe364367dba7
Create Date: 2021-02-06 20:09:56.612787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c1f1a5fd57'
down_revision = 'fe364367dba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=1500), nullable=False),
    sa.Column('condition', sa.String(length=1500), nullable=False),
    sa.Column('ram', sa.String(length=1500), nullable=True),
    sa.Column('screen_size', sa.String(length=1500), nullable=True),
    sa.Column('colour', sa.String(length=1500), nullable=True),
    sa.Column('camera', sa.String(length=1500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phones')
    # ### end Alembic commands ###
