"""empty message

Revision ID: 5cffea07a75f
Revises: 8bd427de693e
Create Date: 2021-03-07 23:38:02.911073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cffea07a75f'
down_revision = '8bd427de693e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('item_category', sa.String(length=30000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'item_category')
    # ### end Alembic commands ###
