"""empty message

Revision ID: 6b4282a92b98
Revises: a38b50fc7870
Create Date: 2021-02-20 17:57:13.116541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4282a92b98'
down_revision = 'a38b50fc7870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('religion', sa.String(length=150), nullable=True),
    sa.Column('level', sa.String(length=150), nullable=True),
    sa.Column('based', sa.String(length=150), nullable=True),
    sa.Column('budget', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomie')
    # ### end Alembic commands ###
