"""empty message

Revision ID: 6d00ec30ba26
Revises: e61a1b70356d
Create Date: 2021-02-19 06:20:31.755504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d00ec30ba26'
down_revision = 'e61a1b70356d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roomie', sa.Column('budget', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roomie', 'budget')
    # ### end Alembic commands ###
