"""empty message

Revision ID: 81043effa7e0
Revises: 51441e35a980
Create Date: 2021-03-31 20:06:01.190921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81043effa7e0'
down_revision = '51441e35a980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_claimers_messages_read_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_lost_item_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_lost_item_read_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_claimers_messages_read_time')
    # ### end Alembic commands ###
