"""empty message

Revision ID: 8f4d1d17fecd
Revises: b8aa526d2850
Create Date: 2021-03-02 17:05:12.147149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4d1d17fecd'
down_revision = 'b8aa526d2850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reported__post', sa.Column('report_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reported__post', 'report_type')
    # ### end Alembic commands ###
