"""empty message

Revision ID: 8f8a40e288c1
Revises: 6ef09f4339bb
Create Date: 2021-02-11 09:48:50.014005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8a40e288c1'
down_revision = '6ef09f4339bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bicycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=1500), nullable=False),
    sa.Column('year_of_manufacture', sa.String(length=1500), nullable=False),
    sa.Column('condition', sa.String(length=1500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes_and_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('subtype', sa.String(length=1500), nullable=True),
    sa.Column('type', sa.String(length=1500), nullable=True),
    sa.Column('level', sa.String(length=1500), nullable=True),
    sa.Column('duration', sa.String(length=1500), nullable=True),
    sa.Column('service_features', sa.String(length=1500), nullable=True),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cleaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('round_the_clock_service', sa.Boolean(), nullable=True),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('computer_and_IT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dj_and_entertainmment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('round_the_clock_service', sa.Boolean(), nullable=True),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electrical_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gfx_design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_and_beauty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals_and_drink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motorcycle_and_scooters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=1500), nullable=False),
    sa.Column('year_of_manufacture', sa.String(length=1500), nullable=False),
    sa.Column('condition', sa.String(length=1500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transmission', sa.String(length=1500), nullable=False),
    sa.Column('mileage', sa.String(length=1500), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party_and_catering_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('round_the_clock_service', sa.Boolean(), nullable=True),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photography',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('type_of_service', sa.String(length=1500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('service_include', sa.String(length=1500), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plumbing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('round_the_clock_service', sa.Boolean(), nullable=True),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repairs_and_installation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_files', sa.ARRAY(sa.String(length=1500)), nullable=True),
    sa.Column('title', sa.String(length=1500), nullable=False),
    sa.Column('date_of_post', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=1500), nullable=False),
    sa.Column('type', sa.String(length=1500), nullable=False),
    sa.Column('condition', sa.String(length=1500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ad_type', sa.String(length=1500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_parts')
    op.drop_table('repairs_and_installation')
    op.drop_table('repairs')
    op.drop_table('printing')
    op.drop_table('plumbing')
    op.drop_table('photography')
    op.drop_table('party_and_catering_event')
    op.drop_table('motorcycle_and_scooters')
    op.drop_table('meals_and_drink')
    op.drop_table('labour')
    op.drop_table('health_and_beauty')
    op.drop_table('gfx_design')
    op.drop_table('electrical_works')
    op.drop_table('dj_and_entertainmment')
    op.drop_table('computer_and_IT')
    op.drop_table('cleaning')
    op.drop_table('classes_and_courses')
    op.drop_table('bicycles')
    # ### end Alembic commands ###
