"""empty message

Revision ID: 93eac68d3f19
Revises: e9bb271dd459
Create Date: 2021-02-13 16:11:35.042913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93eac68d3f19'
down_revision = 'e9bb271dd459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_Lost_and_found', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('whatssap_number', sa.String(length=11), nullable=True))
    op.create_unique_constraint(None, 'user', ['whatssap_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'whatssap_number')
    op.drop_column('user', 'address')
    op.drop_column('post', 'is_Lost_and_found')
    # ### end Alembic commands ###
