"""empty message

Revision ID: 9868727f0643
Revises: ab63ef6ef21c
Create Date: 2021-01-29 16:30:00.487867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9868727f0643'
down_revision = 'ab63ef6ef21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomie_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roomie_request_timestamp'), 'roomie_request', ['timestamp'], unique=False)
    op.create_table('roomies',
    sa.Column('request_sender_id', sa.Integer(), nullable=True),
    sa.Column('requested_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requested_user_id'], ['user.id'], )
    )
    op.add_column('user', sa.Column('last_RoomieRequest_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_RoomieRequest_read_time')
    op.drop_table('roomies')
    op.drop_index(op.f('ix_roomie_request_timestamp'), table_name='roomie_request')
    op.drop_table('roomie_request')
    # ### end Alembic commands ###
