"""empty message

Revision ID: 98a711efbaac
Revises: ef3e3201df85
Create Date: 2021-02-25 16:17:46.532046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a711efbaac'
down_revision = 'ef3e3201df85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_Lost_and_searching', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_Lost_and_searching')
    # ### end Alembic commands ###
