"""empty message

Revision ID: 99441ddbc115
Revises: 2291336e19b0
Create Date: 2021-02-02 13:33:55.742765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99441ddbc115'
down_revision = '2291336e19b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last__message__read__time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_last__message__read__time_timestamp'), 'last__message__read__time', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_last__message__read__time_timestamp'), table_name='last__message__read__time')
    op.drop_table('last__message__read__time')
    # ### end Alembic commands ###
