"""empty message

Revision ID: a5d8cf9e35f6
Revises: 99441ddbc115
Create Date: 2021-02-02 17:34:52.612498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5d8cf9e35f6'
down_revision = '99441ddbc115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_messages_timestamp'), 'tracked_messages', ['timestamp'], unique=False)
    op.drop_index('ix_last__message__read__time_timestamp', table_name='last__message__read__time')
    op.drop_table('last__message__read__time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last__message__read__time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='last__message__read__time_pkey')
    )
    op.create_index('ix_last__message__read__time_timestamp', 'last__message__read__time', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_tracked_messages_timestamp'), table_name='tracked_messages')
    op.drop_table('tracked_messages')
    # ### end Alembic commands ###
