"""empty message

Revision ID: a5fc14112c11
Revises: 254fd0db045d
Create Date: 2021-03-02 17:42:28.328915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fc14112c11'
down_revision = '254fd0db045d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reported__post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('inappropriate_count', sa.Integer(), nullable=True),
    sa.Column('offensive_count', sa.Integer(), nullable=True),
    sa.Column('hate_speech_count', sa.Integer(), nullable=True),
    sa.Column('inaccurate_info_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reported__post')
    # ### end Alembic commands ###
