"""empty message

Revision ID: a6b4cb7058d3
Revises: df180ca9fa8d
Create Date: 2021-02-04 08:24:18.644974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6b4cb7058d3'
down_revision = 'df180ca9fa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specific__message__read__time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specific__message__read__time',
    sa.Column('message_sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_read_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_sender_id'], ['user.id'], name='specific__message__read__time_message_sender_id_fkey'),
    sa.PrimaryKeyConstraint('message_sender_id', name='specific__message__read__time_pkey')
    )
    # ### end Alembic commands ###
