"""empty message

Revision ID: ab63ef6ef21c
Revises: 6a9cb79860c7
Create Date: 2021-01-28 09:50:27.556306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab63ef6ef21c'
down_revision = '6a9cb79860c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_student', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_student')
    # ### end Alembic commands ###
