"""empty message

Revision ID: ae17d334e5de
Revises: e9a40b3419bd
Create Date: 2021-03-13 20:56:05.816071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae17d334e5de'
down_revision = 'e9a40b3419bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claimers_messages', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.add_column('claimers_messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.alter_column('claimers_messages', 'date_of_message',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_claimers_messages_date_of_message'), 'claimers_messages', ['date_of_message'], unique=False)
    op.drop_constraint('claimers_messages_claimer_id_fkey', 'claimers_messages', type_='foreignkey')
    op.create_foreign_key(None, 'claimers_messages', 'user', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'claimers_messages', 'user', ['sender_id'], ['id'])
    op.drop_column('claimers_messages', 'claimer_id')
    op.add_column('user', sa.Column('last_lost_item_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_lost_item_read_time')
    op.add_column('claimers_messages', sa.Column('claimer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'claimers_messages', type_='foreignkey')
    op.drop_constraint(None, 'claimers_messages', type_='foreignkey')
    op.create_foreign_key('claimers_messages_claimer_id_fkey', 'claimers_messages', 'user', ['claimer_id'], ['id'])
    op.drop_index(op.f('ix_claimers_messages_date_of_message'), table_name='claimers_messages')
    op.alter_column('claimers_messages', 'date_of_message',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('claimers_messages', 'sender_id')
    op.drop_column('claimers_messages', 'recipient_id')
    # ### end Alembic commands ###
