"""empty message

Revision ID: b8aa526d2850
Revises: 39550e1b4a3c
Create Date: 2021-03-02 16:53:57.516765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8aa526d2850'
down_revision = '39550e1b4a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reported__post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('inappropriate_count', sa.Integer(), nullable=False),
    sa.Column('offensive_count', sa.Integer(), nullable=False),
    sa.Column('hate_speech_count', sa.Integer(), nullable=False),
    sa.Column('inaccurate_info_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reported__post')
    # ### end Alembic commands ###
