"""empty message

Revision ID: c229438f638f
Revises: a32c49658c48
Create Date: 2021-02-11 13:21:37.571959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c229438f638f'
down_revision = 'a32c49658c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoes')
    op.drop_table('mobile__accessories')
    op.drop_table('plumbing')
    op.drop_table('electrical_works')
    op.drop_table('jewelries')
    op.drop_table('meals_and_drink')
    op.drop_table('hair__weaves')
    op.drop_table('clothing')
    op.drop_table('printing')
    op.drop_table('vehicle_parts')
    op.drop_table('computer__software')
    op.drop_table('computer__accessories')
    op.drop_table('cameras')
    op.drop_table('gfx_design')
    op.drop_table('cleaning')
    op.drop_table('photography')
    op.drop_table('health_and_beauty')
    op.drop_table('tablets')
    op.drop_table('music__equipment')
    op.drop_table('bath_and_body')
    op.drop_table('computer_and_IT')
    op.drop_table('party_and_catering_event')
    op.drop_table('labour')
    op.drop_table('bicycles')
    op.drop_table('repairs')
    op.drop_table('dj_and_entertainmment')
    op.drop_table('skin__care')
    op.drop_table('video__games')
    op.drop_table('makeup')
    op.drop_table('bags')
    op.drop_table('repairs_and_installation')
    op.drop_table('phones')
    op.drop_table('fragrance')
    op.drop_table('laptops')
    op.drop_table('classes_and_courses')
    op.drop_table('motorcycle_and_scooters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorcycle_and_scooters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('year_of_manufacture', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('transmission', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('mileage', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='motorcycle_and_scooters_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='motorcycle_and_scooters_pkey')
    )
    op.create_table('classes_and_courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subtype', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('service_features', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='classes_and_courses_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='classes_and_courses_pkey')
    )
    op.create_table('laptops',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('storage_capacity', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ram', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subtype', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('processor', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('number_of_cores', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('graphics_card', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('graphics_card_memory', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('storage_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('operating_system', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('screen_size', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('camera', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='laptops_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='laptops_pkey')
    )
    op.create_table('fragrance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('formulation', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('scent', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('volume', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='fragrance_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fragrance_pkey')
    )
    op.create_table('phones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ram', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('screen_size', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('colour', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('camera', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='phones_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='phones_pkey')
    )
    op.create_table('repairs_and_installation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='repairs_and_installation_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='repairs_and_installation_pkey')
    )
    op.create_table('bags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('closure', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='bags_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bags_pkey')
    )
    op.create_table('makeup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('tone', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='makeup_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='makeup_pkey')
    )
    op.create_table('video__games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='video__games_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='video__games_pkey')
    )
    op.create_table('skin__care',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('target_area', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('skin_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('benefits', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='skin__care_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='skin__care_pkey')
    )
    op.create_table('dj_and_entertainmment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('round_the_clock_service', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='dj_and_entertainmment_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dj_and_entertainmment_pkey')
    )
    op.create_table('repairs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('round_the_clock_service', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='repairs_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='repairs_pkey')
    )
    op.create_table('bicycles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('year_of_manufacture', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='bicycles_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bicycles_pkey')
    )
    op.create_table('labour',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='labour_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='labour_pkey')
    )
    op.create_table('party_and_catering_event',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('round_the_clock_service', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='party_and_catering_event_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='party_and_catering_event_pkey')
    )
    op.create_table('computer_and_IT',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"computer_and_IT_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='computer_and_IT_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='computer_and_IT_pkey')
    )
    op.create_table('bath_and_body',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='bath_and_body_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bath_and_body_pkey')
    )
    op.create_table('music__equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='music__equipment_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='music__equipment_pkey')
    )
    op.create_table('tablets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('storage_capacity', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('operating_system', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ram', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('screen_size', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('colour', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('camera', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='tablets_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tablets_pkey')
    )
    op.create_table('health_and_beauty',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='health_and_beauty_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='health_and_beauty_pkey')
    )
    op.create_table('photography',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_of_service', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('service_include', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='photography_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photography_pkey')
    )
    op.create_table('cleaning',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('round_the_clock_service', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='cleaning_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cleaning_pkey')
    )
    op.create_table('gfx_design',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='gfx_design_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gfx_design_pkey')
    )
    op.create_table('cameras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='cameras_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cameras_pkey')
    )
    op.create_table('computer__accessories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='computer__accessories_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='computer__accessories_pkey')
    )
    op.create_table('computer__software',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='computer__software_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='computer__software_pkey')
    )
    op.create_table('vehicle_parts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='vehicle_parts_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vehicle_parts_pkey')
    )
    op.create_table('printing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='printing_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='printing_pkey')
    )
    op.create_table('clothing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('style', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='clothing_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='clothing_pkey')
    )
    op.create_table('hair__weaves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='hair__weaves_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hair__weaves_pkey')
    )
    op.create_table('meals_and_drink',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='meals_and_drink_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meals_and_drink_pkey')
    )
    op.create_table('jewelries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('main_material', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('main_stone', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='jewelries_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='jewelries_pkey')
    )
    op.create_table('electrical_works',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='electrical_works_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='electrical_works_pkey')
    )
    op.create_table('plumbing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='plumbing_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='plumbing_pkey')
    )
    op.create_table('mobile__accessories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='mobile__accessories_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mobile__accessories_pkey')
    )
    op.create_table('shoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_files', postgresql.ARRAY(sa.VARCHAR(length=1500)), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('date_of_post', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=1500), autoincrement=False, nullable=False),
    sa.Column('colour', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('style', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('upper_material', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('outsole_material', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='shoes_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shoes_pkey')
    )
    # ### end Alembic commands ###
