"""empty message

Revision ID: d8171f184918
Revises: 39a4af4999b6
Create Date: 2021-02-13 10:49:37.714356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8171f184918'
down_revision = '39a4af4999b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_viewers',
    sa.Column('viewer_id', sa.Integer(), nullable=True),
    sa.Column('viewed_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['viewed_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_viewers')
    # ### end Alembic commands ###
