"""empty message

Revision ID: dd2886441909
Revises: 12552f65800b
Create Date: 2021-03-02 17:13:07.739352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2886441909'
down_revision = '12552f65800b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reported__post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=True),
    sa.Column('inappropriate_count', sa.Integer(), nullable=False),
    sa.Column('offensive_count', sa.Integer(), nullable=False),
    sa.Column('hate_speech_count', sa.Integer(), nullable=False),
    sa.Column('inaccurate_info_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reported__post')
    # ### end Alembic commands ###
