"""empty message

Revision ID: de77fcf071c2
Revises: ae17d334e5de
Create Date: 2021-03-18 05:39:55.178928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de77fcf071c2'
down_revision = 'ae17d334e5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_claimer',
    sa.Column('claimer_id', sa.Integer(), nullable=True),
    sa.Column('finder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claimer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['finder_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_claimer')
    # ### end Alembic commands ###
