"""empty message

Revision ID: dea82bc60e1e
Revises: 93eac68d3f19
Create Date: 2021-02-13 18:47:44.526684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea82bc60e1e'
down_revision = '93eac68d3f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('data', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_notification_data'), 'notification', ['data'], unique=False)
    op.drop_index('ix_notification_timestamp', table_name='notification')
    op.drop_column('notification', 'payload_json')
    op.add_column('user', sa.Column('last_notifications_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_notifications_read_time')
    op.add_column('notification', sa.Column('payload_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_notification_timestamp', 'notification', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_notification_data'), table_name='notification')
    op.drop_column('notification', 'data')
    # ### end Alembic commands ###
