"""empty message

Revision ID: e61a1b70356d
Revises: 522075d38491
Create Date: 2021-02-14 15:39:38.435521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61a1b70356d'
down_revision = '522075d38491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('possession', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'possession')
    # ### end Alembic commands ###
