"""empty message

Revision ID: e9a40b3419bd
Revises: 0c6ca4d43be8
Create Date: 2021-03-10 14:30:38.797353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a40b3419bd'
down_revision = '0c6ca4d43be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claimers_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('date_of_message', sa.DateTime(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('claimer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claimer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claimers_messages')
    # ### end Alembic commands ###
