"""empty message

Revision ID: f0000c7cb8a5
Revises: d8171f184918
Create Date: 2021-02-13 10:59:31.626869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0000c7cb8a5'
down_revision = 'd8171f184918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_viewers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_viewers',
    sa.Column('viewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('viewed_post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['viewed_post_id'], ['post.id'], name='post_viewers_viewed_post_id_fkey'),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], name='post_viewers_viewer_id_fkey')
    )
    # ### end Alembic commands ###
