"""empty message

Revision ID: f3e65161ec2a
Revises: 3f60557e55ba
Create Date: 2021-01-28 09:43:46.074343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e65161ec2a'
down_revision = '3f60557e55ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_student', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_student')
    # ### end Alembic commands ###
