"""empty message

Revision ID: fa00134152ee
Revises: 2b2eba712710
Create Date: 2021-02-13 11:25:27.172396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa00134152ee'
down_revision = '2b2eba712710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed__posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.drop_table('post_viewers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_viewers',
    sa.Column('viewed_post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('viewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['viewed_post_id'], ['post.id'], name='post_viewers_viewed_post_id_fkey'),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], name='post_viewers_viewer_id_fkey')
    )
    op.drop_table('viewed__posts')
    # ### end Alembic commands ###
