"""empty message

Revision ID: fe364367dba7
Revises: a6b4cb7058d3
Create Date: 2021-02-04 08:24:46.581572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe364367dba7'
down_revision = 'a6b4cb7058d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specific__message__read__time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_sender_id', sa.Integer(), nullable=True),
    sa.Column('last_read_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specific__message__read__time')
    # ### end Alembic commands ###
